- sequoia/conftest.py
- sequoia/experiment_test.py
- sequoia/settings/active/continual/incremental/incremental_rl_setting.py
- sequoia/settings/active/continual/incremental/incremental_rl_setting_test.py
- sequoia/settings/base/bases.py
- Fix import of monsterkong generating text in stdout
- Fix `get_applicable_methods()` of Setting
- Reduce number of test steps to get test to run faster
> Fix small bugs 

- examples/basic/quick_demo.py
- examples/basic/quick_demo_ewc.py
- sequoia/settings/passive/cl/class_incremental_setting.py
Fixes #100 
Remove video_recorder calls in _after_step()
Fix import bug in quick_demo_ewc.py
> Fix "ffmpeg not installed" error

- requirements.txt
- setup.py
fixed git requirements to have egg tokens - otherwise, they don't install, 
shortened and simplified setup.py, 
black-formatted
> fixed setup

- sequoia/common/config/trainer_config.py
- sequoia/common/hparams/hyperparameters_test.py
- sequoia/methods/baseline_method.py
> Add max_epochs as a tunable hyper-parameter

- scripts/launch_many_sweeps.sh
- scripts/sweep.sh
- sequoia/common/config/config.py
- sequoia/common/metrics/metrics.py
- sequoia/common/metrics/rl_metrics.py
- sequoia/settings/active/continual/rl_results.py
- sequoia/settings/assumptions/iid_results.py
- sequoia/settings/assumptions/incremental_results.py
- sequoia/settings/passive/cl/class_incremental_results.py
- sequoia/settings/passive/cl/class_incremental_setting.py
> Fix missing 'lower_is_better' attribute bug

- sequoia/methods/aux_tasks/ewc.py
> Isse112 with EWC

- sequoia/methods/baseline_method.py
- sequoia/methods/baseline_method_test.py
- sequoia/methods/models/baseline_model/base_model.py
> Fix output head being on wrong device

- sequoia/common/gym_wrappers/transform_wrappers.py
- sequoia/methods/baseline_method_test.py
- sequoia/settings/active/continual/incremental/incremental_rl_setting_test.py
- sequoia/settings/active/continual/incremental/task_incremental/stationary/iid_rl_setting.py
- sequoia/settings/assumptions/iid.py
- sequoia/settings/assumptions/incremental.py
- sequoia/settings/assumptions/incremental_test.py
- sequoia/settings/passive/cl/task_incremental/multi_task/multi_task_setting.py
- sequoia/settings/passive/cl/task_incremental/multi_task/multi_task_setting_test.py
- Fixes #123
- Fixes some failing tests
> Fix MultiTaskSetting calling fit once per task

- sequoia/methods/baseline_method.py
> Fix small bug leftover from PR

- sequoia/common/config/wandb_config.py
> Add wandb login call for SB3 methods, fix str(key)

- requirements.txt
- sequoia/common/gym_wrappers/utils.py
- sequoia/common/metrics/rl_metrics.py
- sequoia/conftest.py
- sequoia/methods/stable_baselines3_methods/base.py
- sequoia/methods/stable_baselines3_methods/dqn.py
- sequoia/settings/active/continual/continual_rl_setting.py
- sequoia/settings/active/continual/wrappers.py
- sequoia/settings/assumptions/incremental.py
- sequoia/settings/assumptions/incremental_results.py
- sequoia/settings/base/objects.py
- sequoia/settings/passive/cl/class_incremental_setting.py
- sequoia/settings/passive/cl/measure_performance_wrapper.py
- sequoia/settings/passive/cl/measure_performance_wrapper_test.py
- sequoia/settings/passive/cl/objects.py
Fixes #127 
Example runs and plots: https://wandb.ai/sequoia/debug?workspace=user-sequoia
> Add MeasureRLPerformanceWrapper, add more Wandb logging

- requirements.txt
- sequoia/settings/passive/cl/class_incremental_setting_test.py
Fixes #128  by fixing some version requirements for pyyaml, which by default was using an older version.
> Fix Google Colab Import Bugs

- sequoia/experiments/experiment.py
Fixes #141
- Fix a bug whereby when checking for any unused command-line arguments,
we could create an RL Setting with the default "dataset" (cartpole
with pixel observations), which would try to add a render wrapper,
which required OpenGL to be installed.
> Fix hidden OpenGL Dependency bug

- sequoia/settings/active/continual/continual_rl_setting.py
> Fix steps per task bug

- sequoia/settings/active/continual/continual_rl_setting_test.py
> Fix failing test for ContinualRL Setting

- sequoia/experiments/hpo_sweep.py
- sequoia/experiments/hpo_sweep_test.py
- sequoia/methods/models/baseline_model/baseline_model.py
- sequoia/methods/models/baseline_model/multihead_model.py
- sequoia/methods/models/baseline_model/multihead_model_test.py
- sequoia/methods/random_baseline.py
- sequoia/settings/base/bases.py
- Fixes #153 by releasing the current trial when a run raises an exception.
- Fixes a bug with the BaselineMethod when it is run on IncrementalRL
using sequoia_sweep (observation space) 
> Fix sequoia_sweep hanging whenever a run raises an exception

- sequoia/methods/stable_baselines3_methods/a2c.py
- sequoia/methods/stable_baselines3_methods/dqn.py
- sequoia/methods/stable_baselines3_methods/ppo.py
> Issue150: restraint HPO search space for SB3 methods

- sequoia/settings/passive/cl/measure_performance_wrapper.py
> Fix typo in measure_performance_wrapper.py

- examples/basic/quick_demo.py
- sequoia/common/gym_wrappers/convert_tensors.py
- sequoia/experiments/hpo_sweep_test.py
- sequoia/methods/baseline_method.py
- sequoia/methods/experience_replay.py
- sequoia/methods/experience_replay_test.py
- sequoia/settings/base/bases.py
- sequoia/settings/passive/cl/class_incremental_setting.py
- sequoia/settings/passive/cl/class_incremental_setting_test.py
- sequoia/utils/generic_functions/concatenate.py
- tests/examples/quick_demo_test.py
> Add HPO Tuning methods to ExperienceReplay

- sequoia/methods/__init__.py
- sequoia/methods/experience_replay.py
- sequoia/methods/hat.py
- sequoia/methods/pnn/__init__.py
- sequoia/methods/pnn/layers.py
- sequoia/methods/pnn/model_rl.py
- sequoia/methods/pnn/model_sl.py
- sequoia/methods/pnn/pnn_method.py
> Add HAT and PNN to the methods

- sequoia/methods/experience_replay.py
> Fix mini bug in experience_replay.py

- sequoia/methods/experience_replay.py
> Add weight decay to ExperienceReplay

- examples/clcomp21/dummy_method.py
- sequoia/client/env_proxy.py
- sequoia/common/gym_wrappers/utils.py
- sequoia/methods/ewc_method_test.py
> Fix bugs with DummyMethod, EnvProxy

- examples/clcomp21/classifier.py
- sequoia/client/setting_proxy.py
- sequoia/methods/random_baseline.py
- sequoia/settings/assumptions/incremental_results.py
> Add components of Online performance to log_dict

- sequoia/settings/passive/cl/class_incremental_setting.py
> Fix call to on_task_switch at test time

- requirements.txt
> Upgrade torchvision requirement to >= 0.9

- sequoia/client/env_proxy.py
- sequoia/client/env_proxy_test.py
- sequoia/client/setting_proxy.py
- sequoia/client/setting_proxy_test.py
- sequoia/common/gym_wrappers/env_dataset_test.py
- sequoia/common/gym_wrappers/transform_wrappers.py
- sequoia/common/gym_wrappers/utils.py
- sequoia/methods/avalanche/ar1_test.py
- sequoia/methods/random_baseline.py
- sequoia/settings/active/continual/gym_dataloader.py
- sequoia/settings/active/continual/gym_dataloader_test.py
- sequoia/settings/base/environment.py
- sequoia/settings/passive/cl/domain_incremental/domain_incremental_setting.py
- sequoia/settings/passive/passive_environment.py
- sequoia/settings/passive/passive_environment_test.py
> Fix #203 (EnvironmentProxy Multiprocessing dataloader bug)

- requirements.txt
- sequoia/common/gym_wrappers/action_limit_test.py
- sequoia/common/gym_wrappers/env_dataset.py
- sequoia/common/gym_wrappers/env_dataset_test.py
- sequoia/common/gym_wrappers/multi_task_environment.py
- sequoia/common/gym_wrappers/observation_limit.py
- sequoia/common/spaces/typed_dict.py
- sequoia/experiments/experiment.py
- sequoia/experiments/hpo_sweep.py
- sequoia/methods/conftest.py
- sequoia/methods/stable_baselines3_methods/base.py
- sequoia/methods/stable_baselines3_methods/base_test.py
- sequoia/settings/assumptions/continual.py
- sequoia/settings/base/bases.py
- sequoia/settings/presets/classic_control/mountaincar_continuous.yaml
- sequoia/settings/presets/monsterkong/monsterkong_mix.yaml
- sequoia/settings/presets/mujoco/half_cheetah.yaml
- sequoia/settings/rl/continual/setting.py
- sequoia/settings/rl/discrete/multienv_wrappers.py
- sequoia/settings/rl/discrete/setting.py
- sequoia/settings/rl/incremental/setting.py
- sequoia/settings/rl/incremental/setting_test.py
- setup.py
> Add support for MT50, CW10 and CW20

- sequoia/README.md
The earlier links were all pointing to 404.
> Fix broken links

- README.md
- sequoia/main.py
- sequoia/settings/assumptions/continual.py
- sequoia/settings/assumptions/incremental.py
- sequoia/utils/parseable.py
- sequoia/utils/readme.py
- setup.py
Improves the command-line experience significantly:
- All settings have a subparser command with their options listed out;
- For each setting, each Method has a subparser command with all its arguments listed out;
- Added a `sequoia sweep` command to replace the previous `sequoia_sweep`
- Added a `sequoia run` command to replace the previous `sequoia`.
- Added a `sequoia info` command to display some info about a setting or method.
> Improved Command-line API

- examples/advanced/procgen_example.py
Adds an example where environments from ProcGen are used with an Incremental RL Setting.
> Add Procgen example

- requirements.txt
- sequoia/utils/utils.py
> Fix argparse error due to wrong nargs
